In [1]:
import geopandas as gpd
import pandas as pd
import numpy as np
import shapely
from shapely import Polygon, MultiPolygon, LineString, Point, simplify
import time

# Read in Data

In [2]:
#takes 45 seconds

gdf = gpd.read_file('data/shapefiles/MAMMALS_TERRESTRIAL_ONLY')

df = pd.read_csv('data/observations.csv')

In [3]:
"Mustela erminea" in gdf['sci_name'].values

True

# Make Mass Table

In [4]:
#df_highest_mass = df[df['body mass'].notnull()].sort_values(by = 'body mass', ascending = False)\
#                    .drop_duplicates(subset = ['species'], keep = 'first')
#
#masses = gdf[['sci_name']].drop_duplicates().merge(df_highest_mass[['species','body mass']], 
#                                                   left_on = 'sci_name', right_on = 'species', how = 'left')\
#                                                   .drop(columns = ['species'])
#
#masses.to_csv('data/masses_from_ipynb.csv', index = False)

In [5]:
#masses.to_csv('data/masses_from_ipynb.csv', index = False)

# Read in Masses

In [6]:
masses = pd.read_csv('data/masses.csv')

In [7]:
masses[masses['sci_name'] == 'Ovibos moschatus']

              sci_name  body mass
3710  Ovibos moschatus      400.0

# Create new Geometries

In [8]:
def has_line(multipoly):
    multi_geos = (shapely.geometry.multipolygon.MultiPolygon,
                  shapely.geometry.collection.GeometryCollection)
    if isinstance(multipoly, multi_geos):
        for geo in multipoly.geoms:
            if isinstance(geo, shapely.geometry.linestring.LineString):
                return(True)
        return(False)
    else:
        return(isinstance(multipoly, shapely.geometry.linestring.LineString))

def remove_line(geometry):
    new_geo = MultiPolygon([g for g in geometry.geoms if not isinstance(g, shapely.geometry.linestring.LineString)])
    return(new_geo)

def area_simplify(geometry, area_min):
    if area_min == 0:
        return(geometry)
    multi_geos = (shapely.geometry.multipolygon.MultiPolygon,
                  shapely.geometry.collection.GeometryCollection)
    if isinstance(geometry, multi_geos):
        new_geo = MultiPolygon([g for g in geometry.geoms if g.area >= area_min])
    else:
        new_geo = geometry
    return(new_geo)

def remove_holes_poly(pgon, area_min):
    new_interiors = [h for h in pgon.interiors if Polygon(h).area >= area_min]
    new_geo = Polygon(pgon.exterior.coords, holes = new_interiors)
    return(new_geo)

def remove_holes(geometry, area_min):
    if area_min == 0:
        return(geometry)
    multi_geos = (shapely.geometry.multipolygon.MultiPolygon,
                  shapely.geometry.collection.GeometryCollection)
    if isinstance(geometry, multi_geos):
        new_geo = MultiPolygon([remove_holes_poly(g, area_min) for g in geometry.geoms])
    else:
        new_geo = remove_holes_poly(geometry, area_min)
    return(new_geo)

In [9]:
gdf = gdf.merge(masses, how = 'left', on = 'sci_name').dropna(subset = 'body mass')\
    .sort_values(by = 'body mass', ascending = False)
gdf = gdf[gdf['presence'] != 5] #drop extinct territories

In [10]:
"Mustela erminea" in gdf['sci_name'].values

True

In [11]:
#collapse each species into one shape
#takes 60 sec
print("Mustela erminea" in gdf['sci_name'].values)
gdf = gdf.sort_values(by = 'body mass', ascending = False)
print("Mustela erminea" in gdf['sci_name'].values)
gdf = gdf.dissolve(by = 'sci_name').reset_index()
print("Mustela erminea" in gdf['sci_name'].values)
gdf = gdf.sort_values(by = 'body mass', ascending = False)
print("Mustela erminea" in gdf['sci_name'].values)
gdf['geometry'] = gdf['geometry'].apply(simplify, tolerance = 0.1)
gdf['geometry'] = gdf['geometry'].apply(area_simplify, area_min = 0.5)
gdf['geometry'] = gdf['geometry'].apply(remove_holes, area_min= 0.1)
print("Mustela erminea" in gdf['sci_name'].values)

print(len(gdf))

True
True
True
True
True
170

In [12]:
print("Mustela erminea" in gdf['sci_name'].values)

True

In [13]:
gdf.loc[10]

sci_name                                     Ammodorcas clarkei
geometry      MULTIPOLYGON (((45.37689999973526 4.3660355932...
id_no                                                      1141
presence                                                      3
origin                                                        1
seasonal                                                      1
compiler                                                   IUCN
yrcompiled                                                 2016
citation      IUCN (International Union for Conservation of ...
subspecies                                                 None
subpop                                                     None
source                                                     None
island                                                     None
tax_comm                                                   None
dist_comm                                                  None
generalisd                                                    0
legend                               Possibly Extant (resident)
kingdom                                                ANIMALIA
phylum                                                 CHORDATA
class                                                  MAMMALIA
order_                                             ARTIODACTYLA
family                                                  BOVIDAE
genus                                                Ammodorcas
category                                                     VU
marine                                                    false
terrestial                                                 true
freshwater                                                false
Shape_Leng                                             3.312136
Shape_Area                                             0.806961
body mass                                                  35.0
Name: 10, dtype: object

In [14]:
# takes 120 seconds
gdf['no_overlap_geometry'] = np.nan
union = Polygon([])

start = time.time()
abs_times = [0]
rel_times = []
j = 0
for i, row in gdf.iterrows():
    print(row['sci_name'])
    this_geo = row['geometry']
    new_geo = this_geo - union
    if has_line(new_geo):
        new_geo = remove_line(new_geo)
    #new_geo = area_simplify(new_geo, 1)
    #new_geo = remove_holes(new_geo, 0.1)
    gdf.loc[i, 'no_overlap_geometry'] = new_geo
    if new_geo.area > 0:
        union = this_geo.union(union)
    if has_line(union):
        union = remove_line(union)
    union = area_simplify(union, area_min = 1)
    j += 1
    rel_times.append(time.time() - abs_times[-1] - start)
    abs_times.append(time.time()-start)
    print(str(j) +f"/{len(gdf)}", rel_times[-1], abs_times[-1])

Loxodonta africana
1/170 0.00177001953125 0.0017709732055664062
Elephas maximus
2/170 0.0015439987182617188 0.0033159255981445312
Loxodonta cyclotis
3/170 0.004177093505859375 0.0074939727783203125
Ceratotherium simum
4/170 0.0064351558685302734 0.013930082321166992
Rhinoceros sondaicus
5/170 0.002222776412963867 0.016153812408447266
Diceros bicornis
6/170 0.004534006118774414 0.020689010620117188
Giraffa camelopardalis
7/170 0.003930091857910156 0.02461981773376465
Bos gaurus
8/170 0.0045680999755859375 0.029187917709350586
Bos mutus
9/170 0.0005319118499755859 0.029720783233642578
Bison bison
10/170 0.0006992816925048828 0.03042006492614746
Bison bonasus
11/170 0.0021958351135253906 0.03261709213256836
Syncerus caffer
12/170 0.004149913787841797 0.03676795959472656
Bos javanicus
13/170 0.0022759437561035156 0.03904390335083008
Camelus ferus
14/170 0.0017211437225341797 0.040766000747680664
Alces alces
15/170 0.005284786224365234 0.0460507869720459
Ovibos moschatus
16/170 0.010590076446533203 0.05664181709289551
Tragelaphus eurycerus
17/170 0.006072044372558594 0.0627138614654541
Ursus arctos
18/170 0.04057598114013672 0.10329103469848633
Ovis ammon
19/170 0.010190010070800781 0.11348199844360352
Bubalus quarlesi
20/170 0.007811784744262695 0.12129378318786621
Cervus canadensis
21/170 0.012730121612548828 0.13402390480041504
Bubalus mindorensis
22/170 0.0014200210571289062 0.13544392585754395
Bubalus depressicornis
23/170 0.008709907531738281 0.14415383338928223
Cervus elaphus
24/170 0.016711950302124023 0.16086578369140625
Panthera tigris
25/170 0.016531944274902344 0.1773989200592041
Cervus albirostris
26/170 0.009338140487670898 0.186737060546875
Hylochoerus meinertzhageni
27/170 0.010869979858398438 0.19760799407958984
Alcelaphus buselaphus

/var/folders/bk/x4w85fh163780035s7038rwm0000gn/T/ipykernel_75650/1423680893.py:17: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'MULTIPOLYGON (((17.047574751673494 -18.83586325998141, 17.12720675199006 -19.201999260557386, 16.71043225174708 -19.480955259877305, 15.557314751474678 -19.222600259993953, 14.909422846387315 -19.24945842836371, 15.35652547537046 -20.8863986789558, 15.141483687722086 -21.101270644924284, 14.429156014538478 -21.168256821994703, 13.883133293466756 -21.07184453709567, 14.264083114743983 -20.826683140214698, 14.128793930995187 -20.673903359452424, 13.855109328532762 -20.711078295826667, 14.108024386915986 -20.337669647835924, 13.669150894598147 -20.03759872340231, 13.680325883832495 -19.449770428862166, 13.082770044502013 -19.44580095445042, 13.46409280204125 -18.918668023510406, 13.208212571852755 -18.80174614716691, 12.704146978000665 -18.967084125731787, 12.855130482585764 -18.464332517831394, 13.438363785560284 -18.056387516470636, 13.512490299088086 -17.22268952799925, 13.813510603721403 -17.31593126234586, 13.340500000274858 -16.974369999875535, 12.425839999616358 -17.20938000058652, 12.607095919940775 -16.553445372106182, 12.264453535102632 -16.01092826322872, 12.806970643980094 -16.25363328514794, 12.949738305678295 -15.397027323052498, 12.878354473480215 -14.91161727741536, 12.535712089541335 -14.469037530557557, 12.578542386521974 -14.254886040258498, 12.878354473480215 -13.384003312802577, 13.263827157097694 -12.870039736444653, 13.706406904854816 -12.627334713626112, 13.828179999507427 -11.311550000032412, 14.053808211479804 -11.28531870499421, 14.310789999658823 -11.699344918433212, 13.964479910838778 -12.296968527563621, 14.520182568171037 -12.912870031626596, 14.006218990913737 -13.569601271481474, 13.920558395153876 -14.226332508638336, 13.378041285377094 -15.15432230113322, 13.635023073556056 -15.796776771131022, 14.272718623565652 -15.8396070699103, 14.310789999658823 -15.21142936527292, 14.729575136683252 -14.973483263341905, 15.253056558413505 -15.04010817285382, 15.40534206278602 -15.278054272986253, 15.424377751731924 -14.897340512054939, 15.69087738348452 -14.659394411023186, 16.157251739276376 -14.659394411023186, 16.595072565246767 -14.345305557805204, 16.57603687720018 -13.96459179777321, 16.99482201332529 -13.878931202013291, 17.10903614340333 -13.583878036841895, 17.661071095854425 -13.62194941293501, 18.62237334355501 -14.173984365386104, 18.831765911167906 -14.469037530557557, 19.14585476258725 -14.326269871557258, 19.793068157069854 -14.392894779270591, 20.69726334063074 -13.717127853167824, 21.20170907341503 -13.726645698540096, 21.867958154145526 -13.936038266152991, 21.71567265067233 -14.297716339037777, 21.896511686665065 -15.125768769513058, 21.601458520594292 -15.249500740466772, 21.544351456454592 -15.43985762183172, 21.886993841292792 -16.029963951275306, 21.999879756345706 -16.084589819164762, 21.999709756600055 -15.296459757511741, 22.448819756926298 -15.364279756305677, 22.99329975847712 -16.288689756926715, 23.706729758571555 -16.480139757044128, 24.55599975918159 -16.984629758056826, 25.19327975855407 -17.77320975862341, 25.76873775963992 -17.81945025962176, 25.86901675971575 -17.87467575947869, 25.916189260525982 -18.000150758650534, 26.34818625948833 -17.93215375888883, 27.91458876186192 -18.912046259527187, 27.984540000120944 -19.11735999966419, 28.258980000726524 -19.20320999984159, 28.088109999976552 -19.085439999856078, 28.19626999926112 -19.022489999913546, 28.90211999963833 -19.25226999956078, 28.296040000145922 -19.136440000005962, 28.206089999753715 -19.321349999802578, 28.366130000199405 -19.489730000838847, 28.078649999897607 -19.35787000040017, 28.218850000027544 -19.606889999673683, 27.938099999815165 -19.55216000018379, 27.948700000304825 -19.40461999971319, 27.75955363675043 -19.49429035946782, 28.013345762796746 -20.43396126080347, 27.527324761828368 -20.146823761007738, 27.411033762598095 -20.484902760953617, 26.399999760280764 -20.699886094467615, 26.399999760280764 -20.199999760780315, 26.74444976174715 -20.199999760780315, 26.88148016517755 -19.994857928750378, 26.099999759981017 -19.999999760280673, 25.999441761428216 -20.12798326091871, 25.299999759781144 -19.999999760280673, 25.27748853376886 -20.289396408317543, 24.708024031184152 -20.49059896337144, 24.412752913516215 -21.05703720140565, 25.32931807397 -21.66397798699444, 24.541750424942222 -22.188124705590667, 23.835496538134805 -21.25552921240319, 23.21546336734059 -21.250184099016906, 23.242638535939705 -23.32218670215451, 23.058929999819668 -23.322630000474078, 23.920910000196386 -23.32054999988253, 23.92046000012897 -23.75950000022476, 23.062871804790007 -23.754646881648227, 23.060822318840405 -23.53002579191407, 22.637417655200693 -23.958013965472105, 22.065607280052006 -23.43385445401981, 22.038378213283977 -21.840954120935862, 21.000744805428496 -21.73205127174873, 20.996952756464566 -19.76537676032916, 20.99727275503369 -19.99676176024701, 20.027205254219155 -20.002267760548648, 20.35503575459643 -19.549085260376444, 20.195407754264522 -19.09051125978675, 19.691659754194347 -18.895479259959814, 18.00891033544366 -18.72335625178954, 18.008719488513634 -18.499546063400032, 17.439259752335772 -18.532679758563972, 17.047574751673494 -18.83586325998141), (14.018482662544898 -17.419346259222436, 15.190929750207829 -18.27332925953766, 16.073780250758034 -18.100670759048228, 16.57781025124217 -18.250580759094703, 17.77024225237807 -17.39445125781924, 18.377758926033664 -17.394667803776088, 17.70866031642049 -16.991266196277877, 17.832392288273525 -16.848498537277635, 17.79432091218041 -16.534409684059654, 17.613481876187677 -16.153695922228962, 17.213732427209777 -16.505856151540115, 16.671215316533676 -16.515373995113748, 16.567039964355555 -16.01344609608835, 16.195323116268867 -16.039481794848882, 15.557627567158534 -16.553445372106182, 15.338717154173366 -16.477302619020634, 15.119806742087519 -16.610552436245882, 14.53338211659144 -17.38917069327283, 13.877535761825387 -17.344902787400045, 14.018482662544898 -17.419346259222436), (16.359851110540376 -18.529052372768717, 15.882584174220312 -18.768628392486278, 15.9361885858346 -19.127190856772586, 16.68399178789076 -18.93859325257648, 16.70817186513949 -18.522997629536917, 15.664819750231345 -18.518859758870747, 16.359851110540376 -18.529052372768717)), ((14.239406169259325 -10.331154841322814, 13.97290653750673 -10.435851125129261, 13.526350000252364 -10.268709999566795, 13.252579999967054 -9.76013000059902, 13.172880000111945 -9.399679998732893, 13.306657454977596 -9.236602779094937, 13.94435300498725 -9.36033475274661, 13.953870848560882 -9.236602779094937, 13.706406904854816 -8.96058530376871, 13.83013887670785 -8.598907229984604, 13.230514702791368 -7.599533607090223, 12.731349999502925 -5.9789700001653046, 13.070910000296351 -5.870899999635242, 16.562880000711516 -5.904780000796336, 16.96519024579912 -7.108797846659134, 17.979270752843036 -6.973151748754162, 18.763021253727914 -7.2012822487766925, 19.390413253968518 -6.891846249504738, 19.70568000053163 -6.999239999426379, 20.045291024361347 -8.142050716867061, 19.778791392608753 -8.551318009418537, 19.493256071010933 -8.532282320472689, 19.361600021523827 -7.999999748289724, 18.532320252977343 -7.920375749241373, 18.527604805317537 -7.998875768401945, 18.216979999427508 -7.989450000117358, 18.209011252467405 -7.993647247622334, 18.181379252550528 -7.999999748289724, 18.15323000036426 -8.008539999121638, 18.52731999991812 -8.000000000099874, 18.598578733721638 -8.370478972526541, 18.89363189709445 -8.656014294124304, 18.617614420868904 -8.970103145543703, 18.39870400788368 -8.989138833590232, 17.63727648602105 -8.322889752859737, 17.453149999872664 -7.8793099994568365, 17.321441503722497 -7.7585310873397475, 17.33111505141852 -7.716927773198108, 17.292027252555727 -7.692862748916696, 17.306289999284104 -7.636920000157829, 17.301180000156933 -7.628670000120337, 17.296079751479397 -7.623188748262066, 17.289166251921017 -7.6218442492127, 17.009098780484408 -7.980247368021594, 15.914546716457835 -8.418068193092608, 15.87647534126404 -8.893960394256737, 15.638529241131607 -9.103352962768952, 14.306031077871978 -9.731530668305652, 14.239406169259325 -10.331154841322814)), ((16.127253851484113 7.873563907348512, 16.422354276928388 7.706426573327747, 15.829860000138922 7.44466000065853, 15.507480000201895 7.527470000040523, 15.59732999957987 7.7674600001789145, 15.453229999464952 7.894709999367024, 15.286310000106482 8.309220000402718, 15.227140635275871 8.525792106851467, 15.04542990496617 8.503847891666908, 15.045383151910983 8.096804117116335, 13.774818881486226 8.072359247081636, 13.752614791939152 7.914031243746933, 13.434741808287868 8.025988780557839, 13.208161406723605 7.979858406040648, 13.208939979496506 7.799035362691882, 13.02763686634836 7.798229284154161, 13.026671016054593 8.001633804956157, 12.39197185241909 7.998111620954603, 12.277144551979518 8.223261050956808, 12.796688774167649 8.588003319997256, 13.11511884286034 8.47668513281269, 13.048031380543819 8.27294800404718, 13.592632501888488 8.275237339831392, 13.544472367405888 8.998461463325896, 13.999879548402475 8.7738837593281, 14.13676384707395 8.548114883495145, 14.023814383227261 8.29913388152346, 14.137313765418014 8.29939576770056, 14.273395049541932 8.367502424497332, 14.181804261257696 8.729100225694935, 14.363616741419548 8.729448721081667, 14.408783288218217 8.910416102920863, 14.545292761150682 8.820159195484639, 14.545102099482335 9.001056183695994, 15.075865232894216 8.854365971512436, 15.467882417939279 9.037603545267473, 15.603840489546997 8.724721490504407, 15.407156208492268 8.376900593487676, 15.49188437006768 8.217730244655115, 15.736733692306132 7.886018560807997, 16.127253851484113 7.873563907348512)), ((18.936983144356702 8.783525118489479, 19.02831975455308 8.997229265318367, 19.274730253998086 8.739483766562614, 19.84427075469165 8.846071266176068, 20.44036525505254 8.549159267086566, 20.169519254709883 8.280877265373533, 20.37454282319277 8.004504245774399, 20.901444370314138 8.025763550593776, 21.051859755123644 8.211149266725329, 20.903459755463416 8.400341766159613, 20.90935725493341 8.828043766706514, 20.463577255286168 9.198870268648022, 20.528640254644074 9.337068266387405, 20.882339254553017 9.399143267347938, 21.446689756027467 9.794469767765634, 21.676630255881662 9.53648376691234, 22.604689256603933 9.336239766851804, 23.647549758014975 9.923969768190318, 23.65530975793905 9.285649767622715, 23.447809757814127 9.01701976604943, 23.586299758227312 8.99731976679385, 23.520109758158867 8.726969765941988, 24.252659758641016 8.711759766899775, 24.203579757999478 8.30399976687579, 24.56068975872546 8.202899766710914, 24.71408975873544 8.206539765497837, 25.339709134069324 8.547059595623864, 29.30343097475975 8.682344882610266, 30.033101200360136 9.0279781472737, 30.20591783224222 9.584831740992115, 30.781973275446376 9.508024347545643, 31.204413931757585 9.104785539820853, 32.03009339759228 9.738446524287724, 32.82889020831652 9.94845565090759, 33.915873680525976 9.74153143093082, 34.14421081507709 8.977115631880963, 34.13977432362617 8.595025062856394, 33.93720541239992 8.429306265471837, 35.75584776935909 8.035415765625146, 36.50328026996851 7.314809765558266, 35.872010268958775 6.940230763239185, 35.39251976877239 6.122599763868038, 35.51351976932193 5.664179762286267, 35.664899769708654 5.889179763635241, 35.94247076901081 5.887408763803478, 35.72925876897705 5.834338764422512, 35.77503076905481 5.644990763213173, 35.53501220956529 5.42295250358302, 35.86141413465464 5.31459397003573, 35.81710815541709 4.777350425381883, 35.947696685353776 4.629332542263057, 34.38951301611286 4.611003637707768, 34.04248809824719 4.2590150835793, 33.87933375275054 4.109057035453873, 33.81612597563333 4.0467932829836855, 34.02306982691101 3.837492626083872, 33.79542976856902 3.8238797618415674, 33.8926753643766 3.309252282566831, 33.71469167947748 3.1531596413044554, 33.524334800810436 3.274036260265234, 33.63291198210237 3.4157346595269473, 33.78707000447719 3.34990997846279, 33.666649767173055 3.719949761572309, 33.01917763414053 3.8873906356693624, 32.403999327506995 3.74399900455046, 32.19300079375171 3.510998965230101, 31.93833918450582 3.6744263161216395, 31.8852577664328 3.5481707611717184, 31.82700710099698 3.8251413739752707, 31.54100036647378 3.6540000441667644, 31.17391210705813 3.7931803884641795, 30.8535691947626 3.486390766620616, 30.771542511177984 3.674640060690308, 30.55864334031793 3.596019029654542, 30.552325075941553 3.860484928236872, 30.222859459696338 3.937526527627199, 29.614999771122598 4.656000137096726, 29.216094971705616 4.336438656518851, 28.7799140073256 4.558080486825077, 28.41193771235561 4.271712303080392, 28.075242996567113 4.410720825605665, 27.29999923687535 5.225998878345592, 27.14999961848764 5.763000011641282, 26.43700027494276 6.078000068748224, 26.52400016807337 6.221000194403473, 26.286588669031914 6.462460040198721, 26.405521393497565 6.645056248047467, 25.20036805843921 7.4889814923020595, 25.17305977938537 7.573321509180346, 25.285107473231335 7.637699601955092, 25.28599929852885 7.782999040473385, 23.768219258611964 7.414286264599468, 22.881051756833187 6.626063263408923, 22.14490925615729 5.622419762861796, 21.96665525663485 5.932250763262175, 21.598149755606812 6.112279763700201, 20.420089755337983 5.970109763554774, 19.99788975490833 6.42385976381712, 19.99047025359937 7.204809765058656, 19.70067975466702 7.54487726497382, 19.378049753993025 7.304381765805886, 18.949864753655504 7.766871265296686, 19.06476975372118 8.41950426580928, 18.936983144356702 8.783525118489479), (29.135156785257493 6.872541996216228, 28.881788013506082 6.749063191613061, 27.976744721591672 7.642933107676811, 29.73979137367303 5.714129934349046, 30.291571636322033 4.26676215574895, 30.214874520442834 4.675813445534118, 30.566690390349265 4.292014313010213, 31.414308972181345 3.9718028483228522, 32.61981095551124 4.00947478603257, 32.71399079843667 4.216670439389304, 31.991689702218025 4.784369729279604, 31.93408415825735 5.130002993943037, 32.394928509043496 5.763663979309229, 33.14380058412968 6.205306484206915, 33.28095345094107 6.452499899250995, 33.19054080241614 7.326488836490682, 32.768615106901734 7.989514927771722, 32.35652481366924 8.125491288891908, 31.607652741281015 6.915774862120259, 31.434836106701027 6.320517573027644, 30.658986635624785 6.377156024730823, 29.745073481456075 6.896573014433102, 29.135156785257493 6.872541996216228)), ((14.840791805697336 9.794336860557735, 14.728579883954524 9.526786492402778, 14.509897067795464 9.518268426946406, 14.194150248735014 10.116299767520331, 14.424641249693991 11.408919769032138, 14.608480249563911 11.51190977001994, 14.038730749124795 11.61118926896961, 14.169910248759038 11.884209768865787, 14.655590192928456 11.963749753531316, 14.658560149731159 12.195839829744386, 14.322150248335333 12.405449769791119, 14.48247024820347 13.041819269443806, 15.086660249570912 11.993599769114098, 15.14249025032484 11.537359769138106, 15.051475159451115 11.028639783499273, 14.936171750725748 11.048044769150806, 15.145940250242404 10.53834976732793, 15.683689717506525 9.98505982894801, 14.985490250674559 10.001099767340463, 14.840791805697336 9.794336860557735)), ((16.738387302532033 11.057117946536039, 16.946319282109243 10.588131439714232, 17.532606264567505 10.143998636527897, 17.60311340256152 9.98417365229227, 17.475609557135385 9.860162969745318, 16.685511141226243 10.071361782520285, 16.32342863692213 10.664113049577622, 15.965707095406174 10.528321652022669, 15.56437060561899 10.607046834443906, 15.54010842926067 10.978088678150016, 16.070145764815265 11.368591328427101, 16.738387302532033 11.057117946536039)), ((12.973287247708356 10.29516676833174, 12.693591748460449 10.209391768015735, 12.753082248047349 10.663696267768614, 12.170443247657829 11.040885769063038, 12.330597747088405 11.364818770469924, 12.9511412480702 11.412302770356632, 13.458755248356056 11.098347769533973, 13.452290248795975 10.834344768196559, 12.973287247708356 10.29516676833174)), ((-1.0397975875885663 15.435256334312442, -0.8313281578681426 15.265969374187307, -0.911548642156049 15.01299707395583, -1.7222274360472625 14.50454336318569, -2.593057344520787 14.98459105543293, -2.3608661563479814 15.278459568854089, -3.06243557624083 15.18689785565158, -3.1274025549838598 15.317916790327672, -2.513118562071952 15.907277328186183, -1.3666942490403358 16.619450007711748, -1.1395320058973084 16.162915500450026, -1.4524411851125478 15.578649157932318, -1.0397975875885663 15.435256334312442), (-1.9857763409053746 14.986508729294485, -2.0681197621173055 14.915831042968307, -1.8768886965560796 14.699098381485157, -1.2680613149776718 14.885451939755285, -1.365031997029007 15.066168805545999, -1.9857763409053746 14.986508729294485)), ((27.103999761679688 -17.979799759051616, 27.357599761719655 -17.589049756540987, 27.631389762027936 -17.503149759453777, 27.700289762062937 -17.198259757581695, 28.106139762140344 -17.0474697574233, 28.116129762378705 -16.848409257980848, 28.387459763457343 -16.758869758532512, 28.441039262052357 -16.92566925773002, 28.651589762557535 -16.73039975864191, 28.801625262995515 -16.89544975720048, 28.94584976255652 -16.77314975785498, 29.055724763587023 -16.592674758433304, 28.710936775312007 -16.539189868517553, 28.764509412079747 -15.938353767312492, 29.30996709810313 -15.621071767747821, 30.6157359415605 -15.26586476844426, 31.852191773131892 -15.465196359524327, 32.69113379748683 -14.750321288296789, 33.701146288670316 -14.770836743321013, 34.572637457852466 -15.074820559521186, 34.422770337481154 -15.651292888855664, 34.084202592875386 -15.953033112388198, 32.603219203903166 -15.907227323881841, 31.752641418166945 -16.217776777376343, 31.715923142239262 -16.193828813349, 31.482023488097674 -16.157374984280626, 32.00389476683006 -16.43422325569867, 31.591697765439562 -16.814071757305726, 31.46331026415743 -16.795844756730105, 31.607559265747568 -16.741777257214608, 31.312820765266167 -16.495288758669233, 31.3927382652588 -16.378276258542428, 31.16202526575347 -16.07440375772717, 31.07817076496889 -16.576499757158047, 30.87431926492218 -16.635749757345366, 30.656105763570167 -16.378909757179485, 30.50519576417321 -16.44314975635615, 30.48976876411723 -16.686439758488007, 30.32292976399748 -16.501299757078073, 30.062239763454386 -16.50750975656996, 30.080969763843598 -16.730049757790027, 29.81012976377764 -16.74657975744981, 29.83229976362327 -16.526049757190492, 29.46926976328899 -16.2458897572065, 29.329819764470585 -16.61557975710008, 29.040909762975218 -16.849689757676117, 29.13356976333398 -17.01758975726142, 28.541489762842332 -17.402793259401335, 28.547619762242277 -17.92423975815825, 28.334409761401446 -18.196579759048575, 27.82499976192952 -18.180649758279685, 27.80663976241516 -18.321359758545952, 27.351059761398915 -18.440629758456566, 27.002959760684462 -18.24132975786199, 27.189609261558246 -18.037539758852745, 27.121455260851633 -17.99505775850872, 26.860860000288824 -18.14533000007941, 27.103999761679688 -17.979799759051616)), ((26.014207061007085 -13.573552516635289, 26.459050928457657 -13.791498011024316, 26.921886201986695 -14.472725006353926, 26.81178311849618 -15.08275550546216, 26.048619055225288 -15.792996419649, 26.039943154253194 -16.756897349233213, 25.866934882239093 -16.90934380527233, 25.209369341322088 -15.602344845738003, 25.353325566821525 -13.872744350171558, 25.65323725099836 -13.599834091869809, 26.014207061007085 -13.573552516635289)), ((24.040330757958145 -12.175687253663796, 24.489665758767785 -12.178317253538353, 25.10971425940562 -12.477136753358423, 25.242208759426774 -12.978001754477361, 25.097887258989886 -13.378120254645978, 24.746425758841724 -13.434249754822304, 24.095142258508474 -12.972912755419259, 22.586

28/170 0.01150202751159668 0.20911002159118652
Rangifer tarandus
29/170 0.061081886291503906 0.27019190788269043
Boselaphus tragocamelus
30/170 0.012786865234375 0.28297996520996094
Oryx leucoryx
31/170 0.012199878692626953 0.2951798439025879
Panthera leo
32/170 0.015149116516113281 0.3103299140930176
Sus scrofa
33/170 0.02727198600769043 0.3376028537750244
Ammotragus lervia
34/170 0.014222145080566406 0.3518249988555908
Ovis canadensis
35/170 0.014333009719848633 0.36615800857543945
Gorilla gorilla
36/170 0.01286005973815918 0.37901806831359863
Ursus americanus
37/170 0.04959583282470703 0.42861390113830566
Ursus thibetanus
38/170 0.022338151931762695 0.45095205307006836
Capra ibex
39/170 0.0015380382537841797 0.45249009132385254
Addax nasomaculatus
40/170 0.015356779098510742 0.4678468704223633
Capra walie
41/170 0.014472007751464844 0.4823188781738281
Capra sibirica
42/170 0.01690506935119629 0.4992239475250244
Beatragus hunteri
43/170 0.002704143524169922 0.5019280910491943
Ailuropoda melanoleuca
44/170 0.0026769638061523438 0.5046050548553467
Lama guanicoe
45/170 0.014586925506591797 0.5191929340362549
Capra falconeri
46/170 0.0013780593872070312 0.5205709934234619
Cervus nippon
47/170 0.015915870666503906 0.5364880561828613
Capra cylindricornis
48/170 0.0026848316192626953 0.5391738414764404
Odocoileus virginianus
49/170 0.026432037353515625 0.565605878829956
Damaliscus pygargus
50/170 0.014375925064086914 0.579981803894043
Capricornis swinhoei
51/170 0.002468109130859375 0.5824499130249023
Capricornis sumatraensis
52/170 0.018800020217895508 0.6012499332427979
Osphranter rufus
53/170 0.014991044998168945 0.6162409782409668
Panthera onca
54/170 0.021229982376098633 0.6374721527099609
Capra pyrenaica
55/170 0.017358779907226562 0.6548318862915039
Cephalophus silvicultor
56/170 0.016680002212524414 0.6715118885040283
Ovis dalli
57/170 0.018156051635742188 0.6896679401397705
Aepyceros melampus
58/170 0.01769709587097168 0.7073650360107422
Capra nubiana
59/170 0.01713871955871582 0.724503755569458
Axis axis
60/170 0.01694011688232422 0.7414438724517822
Pongo pygmaeus
61/170 0.017427921295166016 0.7588717937469482
Puma concolor
62/170 0.04883098602294922 0.8077027797698975
Cephalophus jentinki
63/170 0.0024230480194091797 0.8101258277893066
Oreamnos americanus
64/170 0.024160146713256836 0.8342859745025635
Capra caucasica
65/170 0.0026438236236572266 0.8369309902191162
Antilocapra americana
66/170 0.018393993377685547 0.8553249835968018
Macropus giganteus
67/170 0.017618894577026367 0.8729450702667236
Capra aegagrus
68/170 0.0185089111328125 0.8914539813995361
Orycteropus afer
69/170 0.019125938415527344 0.910581111907959
Crocuta crocuta
70/170 0.020531892776489258 0.9311139583587646
Capreolus pygargus
71/170 0.021347999572753906 0.9524619579315186
Antilope cervicapra
72/170 0.016553878784179688 0.9690158367156982
Macropus fuliginosus
73/170 0.01638507843017578 0.9854018688201904
Pan troglodytes
74/170 0.029951095581054688 1.0153529644012451
Panthera pardus
75/170 0.02874302864074707 1.0440969467163086
Ovis gmelini
76/170 0.018399953842163086 1.0624969005584717
Axis calamianensis
77/170 0.001371145248413086 1.0638689994812012
Acinonyx jubatus
78/170 0.02208113670349121 1.0859501361846924
Myrmecophaga tridactyla
79/170 0.033461809158325195 1.1194119453430176
Catagonus wagneri
80/170 0.0022439956665039062 1.1216559410095215
Capricornis crispus
81/170 0.017991065979003906 1.1396470069885254
Antidorcas marsupialis
82/170 0.025255918502807617 1.1649041175842285
Vombatus ursinus
83/170 0.026904821395874023 1.1918089389801025
Arabitragus jayakari
84/170 0.01741194725036621 1.2092208862304688
Canis rufus
85/170 0.015686988830566406 1.2249078750610352
Canis lupus
86/170 0.0899350643157959 1.3148438930511475
Capreolus capreolus
87/170 0.05248427391052246 1.36732816696167
Ammodorcas clarkei
88/170 0.0023818016052246094 1.3697099685668945
Hyaena hyaena
89/170 0.03934597969055176 1.4090559482574463
Hystrix indica
90/170 0.03815007209777832 1.447206974029541
Arctictis binturong
91/170 0.025040864944458008 1.4722487926483154
Lasiorhinus latifrons
92/170 0.018952131271362305 1.4912009239196777
Papio anubis
93/170 0.02174210548400879 1.512943983078003
Mandrillus sphinx
94/170 0.019635915756225586 1.532580852508545
Papio cynocephalus
95/170 0.02003622055053711 1.552617073059082
Cephalophus dorsalis
96/170 0.03233695030212402 1.584954023361206
Chrysocyon brachyurus
97/170 0.02160787582397461 1.6065618991851807
Lynx lynx
98/170 0.056780099868774414 1.663341999053955
Hystrix cristata
99/170 0.03934001922607422 1.7026829719543457
Colobus angolensis
100/170 0.022024869918823242 1.724707841873169
Cephalophus zebra
101/170 0.002274036407470703 1.7269818782806396
Civettictis civetta
102/170 0.03527402877807617 1.7622568607330322
Cephalophus ogilbyi
103/170 0.02005314826965332 1.782310962677002
Cephalophus niger
104/170 0.019999027252197266 1.8023099899291992
Canis simensis
105/170 0.0009579658508300781 1.8032679557800293
Cephalophus nigrifrons
106/170 0.031793832778930664 1.8350627422332764
Caracal caracal
107/170 0.04366731643676758 1.878730058670044
Cephalophus callipygus
108/170 0.019981861114501953 1.898711919784546
Hystrix brachyura
109/170 0.02759385108947754 1.926306962966919
Hystrix africaeaustralis
110/170 0.033821821212768555 1.9601287841796875
Cephalophus harveyi
111/170 0.020565271377563477 1.980694055557251
Wallabia bicolor
112/170 0.03453397750854492 2.015228033065796
Raphicerus campestris
113/170 0.0364227294921875 2.0516507625579834
Caracal aurata
114/170 0.03691911697387695 2.0885698795318604
Canis lupaster
115/170 0.0232388973236084 2.1118087768554688
Ailurus fulgens
116/170 0.002457141876220703 2.1142659187316895
Cephalophus weynsi
117/170 0.002232074737548828 2.1164979934692383
Gulo gulo
118/170 0.12303495407104492 2.239532947540283
Dendrolagus dorianus
119/170 0.02309894561767578 2.262631893157959
Cephalophus natalensis
120/170 0.035856008529663086 2.2984888553619385
Cephalophus rufilatus
121/170 0.03536796569824219 2.3338568210601807
Canis latrans
122/170 0.04859423637390137 2.3824520111083984
Canis aureus
123/170 0.048948049545288086 2.4314000606536865
Canis adustus
124/170 0.02518486976623535 2.4565861225128174
Proteles cristata
125/170 0.0270998477935791 2.483686923980713
Meles leucurus
126/170 0.048887014389038086 2.5325751304626465
Mellivora capensis
127/170 0.053261756896972656 2.585836887359619
Erythrocebus patas
128/170 0.02699422836303711 2.6128311157226562
Canis mesomelas
129/170 0.024469852447509766 2.6373019218444824
Cephalophus adersi
130/170 0.0009849071502685547 2.638286828994751
Colobus guereza
131/170 0.002855062484741211 2.641141891479492
Cuniculus paca
132/170 0.030793190002441406 2.6719350814819336
Dorcopsis luctuosa
133/170 0.025925874710083008 2.6978609561920166
Dendrolagus scottae
134/170 0.0009860992431640625 2.698848009109497
Dendrolagus inustus
135/170 0.02440500259399414 2.7232537269592285
Choloepus didactylus
136/170 0.039405107498168945 2.7626588344573975
Macaca arctoides
137/170 0.04783511161804199 2.810495138168335
Bradypus torquatus
138/170 0.023502826690673828 2.833997964859009
Atelocynus microtis
139/170 0.0029921531677246094 2.83699107170105
Alouatta palliata
140/170 0.028229951858520508 2.8652219772338867
Choloepus hoffmanni
141/170 0.028636932373046875 2.8938589096069336
Cryptoprocta ferox
142/170 0.024736881256103516 2.918595790863037
Sarcophilus harrisii
143/170 0.02362227439880371 2.942218065261841
Vulpes vulpes
144/170 0.407926082611084 3.350144863128662
Trachypithecus francoisi
145/170 0.0029840469360351562 3.3531289100646973
Bradypus tridactylus
146/170 0.02477717399597168 3.377906084060669
Euphractus sexcinctus
147/170 0.04129981994628906 3.419205904006958
Bradypus variegatus
148/170 0.04978013038635254 3.468986988067627
Cabassous tatouay
149/170 0.04192996025085449 3.510917901992798
Allenopithecus nigroviridis
150/170 0.0030260086059570312 3.513943910598755
Capromys pilorides
151/170 0.02476215362548828 3.538706064224243
Lepus arcticus
152/170 0.10355782508850098 3.642263889312744
Felis lybica
153/170 0.06826210021972656 3.7105259895324707
Viverra tangalunga
154/170 0.05062985420227051 3.7611570358276367
Lepus timidus
155/170 0.10014581680297852 3.8613028526306152
Bradypus pygmaeus
156/170 0.03000330924987793 3.891306161880493
Chaetophractus villosus
157/170 0.027915000915527344 3.9192211627960205
Rattus norvegicus
158/170 0.13042187690734863 4.0496437549591064
Mustela erminea
159/170 0.1586763858795166 4.20832085609436
Sciurus vulgaris
160/170 0.06362628936767578 4.271947860717773
Mustela nivalis
161/170 0.14281225204467773 4.414761066436768
Rattus rattus
162/170 0.08166193962097168 4.496423959732056
Pteromys volans
163/170 0.07128190994262695 4.567705869674683
Alexandromys oeconomus
164/170 0.07674026489257812 4.644446134567261
Mus musculus
165/170 0.20148181915283203 4.845927953720093
Lasiurus cinereus
166/170 0.10177397727966309 4.947702884674072
Sorex tundrensis
167/170 0.11060404777526855 5.058306932449341
Sorex caecutiens
168/170 0.2507209777832031 5.30902886390686
Sorex minutus
169/170 0.09478211402893066 5.403811931610107
Sorex minutissimus
170/170 0.08005714416503906 5.483870029449463

In [15]:
geos = gdf['no_overlap_geometry']
a_gdf = gdf.drop(columns = ['geometry','no_overlap_geometry'])
new_gdf = gpd.GeoDataFrame(a_gdf, crs="EPSG:4326", geometry=geos)
new_gdf.to_file('data/shapefiles/largest-mammals')

In [16]:
geo = new_gdf[new_gdf['sci_name'] == 'Loxodonta africana']['geometry'].values[0]

In [17]:
new_gdf

,sci_name,id_no,presence,origin,seasonal,compiler,yrcompiled,citation,subspecies,subpop,...,family,genus,category,marine,terrestial,freshwater,Shape_Leng,Shape_Area,body mass,geometry
114,Loxodonta africana,181008073,1,1,1,IUCN SSC African Elephant Specialist Group,2021,IUCN SSC African Elephant Specialist Group,None,None,...,ELEPHANTIDAE,Loxodonta,EN,false,true,false,518.449852,139.321987,6000.000,"MULTIPOLYGON (((17.04757 -18.83586, 17.12721 -..."
96,Elephas maximus,7140,3,1,1,"IUCN/SSC AsESG, WCS, WWF",2020,"IUCN/SSC AsESG, WCS, WWF",None,None,...,ELEPHANTIDAE,Elephas,EN,false,true,false,214.858199,22.409475,4500.000,"MULTIPOLYGON (((80.85750 9.18414, 81.22670 8.6..."
115,Loxodonta cyclotis,181007989,4,1,1,IUCN SSC African Elephant Specialist Group,2021,IUCN SSC African Elephant Specialist Group,None,None,...,ELEPHANTIDAE,Loxodonta,CR,false,true,false,338.198945,80.191725,2700.000,"MULTIPOLYGON (((-8.59336 5.76309, -8.17966 5.5..."
75,Ceratotherium simum,4185,1,6,1,IUCN (International Union for Conservation of ...,2020,IUCN (International Union for Conservation of ...,simum,None,...,RHINOCEROTIDAE,Ceratotherium,NT,false,true,false,99.896073,129.692495,2000.000,"MULTIPOLYGON (((-6.18354 10.22858, -5.67630 10..."
152,Rhinoceros sondaicus,19495,1,1,1,IUCN,2020,IUCN (International Union for Conservation of ...,None,None,...,RHINOCEROTIDAE,Rhinoceros,CR,false,true,false,30.961061,10.314619,1750.000,"POLYGON ((112.82462 -7.29655, 112.74430 -7.545..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,Lasiurus cinereus,11345,1,1,1,IUCN,2008,IUCN (International Union for Conservation of ...,semotus,None,...,VESPERTILIONIDAE,Lasiurus,LC,false,true,false,14.193316,5.157868,0.026,"MULTIPOLYGON (((-155.20850 19.97254, -154.8099..."
158,Sorex tundrensis,41422,1,1,1,IUCN,2012,IUCN (International Union for Conservation of ...,None,None,...,SORICIDAE,Sorex,LC,false,true,false,953.025010,2698.008609,0.010,"MULTIPOLYGON (((109.24414 74.03702, 109.59921 ..."
155,Sorex caecutiens,29662,1,1,1,IUCN,2012,IUCN (International Union for Conservation of ...,None,None,...,SORICIDAE,Sorex,LC,false,true,false,3.681864,0.171832,0.010,"MULTIPOLYGON (((179.99900 69.06873, 179.99900 ..."
157,Sorex minutus,29667,1,1,1,IUCN,2008,IUCN (International Union for Conservation of ...,None,None,...,SORICIDAE,Sorex,LC,false,true,false,1357.221893,2064.400425,0.004,"MULTIPOLYGON (((-9.94110 52.56108, -9.94110 52..."
156,Sorex minutissimus,29666,1,1,1,IUCN,2008,IUCN (International Union for Conservation of ...,None,None,...,SORICIDAE,Sorex,LC,false,true,false,741.607164,2824.451116,0.003,"MULTIPOLYGON (((10.63619 63.54997, 10.63621 63..."